version: 0.2
phases:
  pre_build:
    commands:
    - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay &
    - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - mvn package
    - echo Building the Docker image...
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
