version: 0.2
phases:
  pre_build:
    commands:
    - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 &
    - sleep 5;
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - mvn package
    - echo Building the Docker image...
    - docker build -t redwine ./redwine.distribution/target/redwine.distribution-1.0-SNAPSHOT-dist
    - docker tag redwine:latest 432127854945.dkr.ecr.eu-west-1.amazonaws.com/redwine:latest
  post_build:
    commands:
    - echo Pushing the Docker image...
    - docker push 432127854945.dkr.ecr.eu-west-1.amazonaws.com/redwine:latest
