# https://hub.docker.com/r/teimatinimarin/builder/
# docker login
# docker build -t builder .
# docker tag xxxxx teimatinimarin/builder:1.0.0
# docker push teimatinimarin/builder

FROM ubuntu:18.04

RUN apt-get update && apt-get upgrade -y && apt-get install -y wget

# Install Java 11
RUN wget https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz && \
    echo '7a6bb980b9c91c478421f865087ad2d69086a0583aeeb9e69204785e8e97dcfd' && \
    sha256sum openjdk-11.0.1_linux-x64_bin.tar.gz
RUN mkdir -p /opt/java && \
    tar -xf openjdk-11.0.1_linux-x64_bin.tar.gz --directory /opt/java && \
    rm openjdk-11.0.1_linux-x64_bin.tar.gz
ENV JAVA_HOME=/opt/java/jdk-11.0.1
ENV PATH=$PATH:/opt/java/jdk-11.0.1/bin

# Install Maven 3.6.0
RUN wget https://www-eu.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz && \
    echo 'fae9c12b570c3ba18116a4e26ea524b29f7279c17cbaadc3326ca72927368924d9131d11b9e851b8dc9162228b6fdea955446be41207a5cfc61283dd8a561d2f' && \
    sha512sum apache-maven-3.6.0-bin.tar.gz
RUN mkdir -p /opt/maven && \
    tar -xf apache-maven-3.6.0-bin.tar.gz --directory /opt/maven && \
    rm apache-maven-3.6.0-bin.tar.gz
ENV PATH=$PATH:/opt/maven/apache-maven-3.6.0/bin

# Install Docker CE 18.06.01
RUN wget https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_18.06.1~ce~3-0~ubuntu_amd64.deb
RUN apt-get install -y libltdl7 libdevmapper1.02.1 iptables && \
    dpkg -i docker-ce_18.06.1~ce~3-0~ubuntu_amd64.deb && \
    rm docker-ce_18.06.1~ce~3-0~ubuntu_amd64.deb
