FROM teimatinimarin/base:1
RUN apt-get install -y docker.io
RUN wget https://www-us.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz && \
    sha256sum apache-maven-3.5.4-bin.tar.gz

RUN mkdir -p /opt/apache/maven && \
    tar -xf apache-maven-3.5.4-bin.tar.gz --directory /opt/apache/maven && \
    rm apache-maven-3.5.4-bin.tar.gz

ENV MAVEN_HOME=/opt/apache/maven/apache-maven-3.5.4
ENV PATH=$PATH:/opt/apache/maven/apache-maven-3.5.4/bin
