# https://hub.docker.com/r/teimatinimarin/redwine/
# docker login
# docker build -t teimatinimarin/redwine:1 .
# docker push teimatinimarin/redwine

FROM teimatinimarin/base:latest

# Add user and group
RUN groupadd --gid 500 ec2-user && \
    useradd -ms /bin/bash --uid 500 --gid 500 ec2-user

# Install Redwine
COPY . /home/ec2-user/redwine
RUN mkdir /home/ec2-user/redwine/logs && \
    chown -R ec2-user:ec2-user /home/ec2-user/redwine && \
    chmod 700 /home/ec2-user/redwine/entrypoint*

USER ec2-user
WORKDIR /home/ec2-user/redwine
CMD ["./entrypoint.sh"]
